<?php

namespace PhpTaskman\Drupal\Robo\Plugin\Commands;

/**
 * Class Drupal8Commands.
 */
class Drupal8Commands extends AbstractDrupalCommands
{
    /**
     * Disable aggregation and clear cache.
     *
     * @command drupal:disable-cache
     *
     * @return \Robo\Collection\CollectionBuilder
     *   Collection builder.
     */
    public function disableDrupalCache()
    {
        $tasks = [];

        $tasks[] = $this->taskExecStack()
            ->stopOnFail()
            ->exec('./vendor/bin/drush -y config-set system.performance css.preprocess 0')
            ->exec('./vendor/bin/drush -y config-set system.performance js.preprocess 0')
            ->exec('./vendor/bin/drush cache:rebuild');

        // Build and return task collection.
        return $this->collectionBuilder()->addTaskList($tasks);
    }

    /**
     * @param string $settings_override_filename
     *
     * @return string
     */
    protected function getSettingsSetupAddendum($settings_override_filename)
    {
        return <<< EOF
/**
 * Include Drupal 8 settings overrides.
 *
 * The following file is generated by the openeuropa/task-runner project
 * using configuration from your local "runner.yml.dist/runner.yml" files.
 *
 * Keep this code block at the end of the file.
 */
if (file_exists(\$app_root . '/' . \$site_path . '/${settings_override_filename}')) {
  include \$app_root . '/' . \$site_path . '/${settings_override_filename}';
}
EOF;
    }
}
